// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntpgqrexunprgbcjnllg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50cGdxcmV4dW5wcmdiY2pubGxnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzA0MzcsImV4cCI6MjA2MzY0NjQzN30.I4PennTompgrQnPv-bOgF4VaRCt4a8iRPm9_oc-Afy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);